[package]
name = "fhers_protos"
description = "Protos for the fhers library"
version = "0.0.1"
edition = "2021"
license = "MIT"
repository = "https://github.com/tlepoint/fhe.rs"

[lib]
bench = false

[dependencies]
protobuf = "3.1.0"
