[package]
name = "fhers-traits"
description = "Traits for the fhers library"
version = "0.0.1-beta"
edition = "2021"
license = "MIT"
repository = "https://github.com/tlepoint/fhe.rs"

[lib]
bench = false  # Disable default bench (we use criterion)

[dependencies]
