[package]
name = "fhe-traits"
description = "Traits for the fhe.rs library"
version = "0.1.0-beta.2"
edition = "2021"
license = "MIT"
repository = "https://github.com/tlepoint/fhe.rs"
homepage = "https://fhe.rs/"

[lib]
bench = false  # Disable default bench (we use criterion)

[dependencies]
rand = "0.8.5"
