[package]
name = "fhe-traits"
description = "Traits for the fhe.rs library"
version = "0.0.1-alpha"
edition = "2021"
license = "MIT"
repository = "https://github.com/tlepoint/fhe.rs"

[lib]
bench = false  # Disable default bench (we use criterion)

[dependencies]
