[package]
name = "fhers"
description = "Fully homomorphic encryption in Rust"
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/tlepoint/fhe.rs"

[lib]
bench = false  # Disable default bench (we use criterion)

[dependencies]
math = { version = "0.1.0", path = "../math" }
util = { version = "0.1.0", path = "../util" }
