[package]
name = "rlwe"
description = "RLWE for the fhers library"
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/tlepoint/fhe.rs"

[lib]
bench = false  # Disable default bench (we use criterion)
